### ISSUE TITLE
Rendering problems: sadist04.zip/K!LIGHT.RIP

### ISSUE THREAD

**Issue by sjs** [andyherbert/ripscript.js#1]
I'm not sure if you have any intention of maintaining this project, but if you do, I've noticed some rendering errors.

Here's how the file renders:
![rendered by ripscrip.js](http://i.imgur.com/hSxxE14.png)

Here's how the file *should* render (as rendered by PabloDraw):
![rendered by PabloDraw](http://i.imgur.com/ce7Xn4g.png)

You can grab the pack here: http://files.artpacks.org/1999/sadist05.zip

**Comment by andyherbert** [comment]
Yeah, it's very much incomplete and broken. I originally posted it on Github in the hopes that someone might see it, get inspired and have a try themselves. I stopped when I realised that I needed the vector font definitions, and couldn't get them. I think that it was either Chris Wirth or Curtis Wensley who has since provided them for me, but I had lost interest by then.

**Comment by sjs** [comment]
Doh! I was so excited when I had found this repo, too! Should have known it was too good to be true! :)

I completely understand though.  Thanks for all of the work you've put in so far on this! Feel free to mark this as closed.
